version: "3.0"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "gdrive_clone"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/var/data
    ports:
      - "5432:5432"