version: "3.0"

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    volumes:
      - .:/var/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "gdrive_clone"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/var/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .:/var/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} && mc mb myminio/${MINIO_BUCKET_NAME} && mc policy set download myminio/${MINIO_BUCKET_NAME}"