spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gdrive_clone
    username: postgres
    password: postgres

  jpa:
    show-sql: true

  session:
    store-type: redis

  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration

  minio:
    url: http://localhost:9001
    bucket: files-bucket
    access-key: minioadmin
    secret-key: minioadmin
    port: 9000

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 10MB
