alter table if exists user_role drop constraint if exists user_role_user_fk;
drop table if exists user_role cascade;
drop table if exists usr cascade;

create table user_role (
                           user_id bigint not null,
                           roles varchar(255)
);

create table usr (
    id int8 GENERATED BY DEFAULT AS IDENTITY,
    password varchar(255),
    username varchar(255),
    primary key (id)
                 );

alter table if exists user_role
    add constraint user_role_user_fk
        foreign key (user_id) references usr;

-- create default user.  username:user password: 1234
insert into usr (password, username) values ('$2a$08$Y.lWUzhf08mk4BUNdloK1e4ue7Rl3fqbamoOrGfFAGlTlsMDSXlDC', 'user');
insert into user_role (user_id, roles) values (1, 1);